sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t Gaurav-Pancholi/Docker-KubernetesAWS -f Dockerfile.dev .

script:
  - docker run -e CI=true Gaurav-Pancholi/Docker-KubernetesAWS npm run test
